export enum POSITIVE_KEYS {
  OPEN = 'OPEN',
  ONLINE = 'ONLINE',
  ACTIVE = 'ACTIVE',
  DONE = 'DONE',
  VERIFIED = 'VERIFIED',
  AVAILABLE = 'AVAILABLE',
  UPDATED = 'UPDATED',
  CREATED = 'CREATED',
  OPERATIVE = 'OPERATIVE',
  ASSIGNED = 'ASSIGNED',
  COMPLETED = 'COMPLETED',
  CONFIRMED = 'CONFIRMED',
  AUTOMATED = 'AUTOMATED',
  AFFILIATED = 'AFFILIATED'
}

export enum PROCESS_KEYS {
  IN_PROGRESS = 'IN_PROGRESS',
  IN_PROCESS = 'IN_PROCESS',
  INCOMING = 'INCOMING',
  IN_CHECK = 'IN_CHECK',
  PENDING = 'PENDING',
  VERIFIED_ARRIVAL = 'VERIFIED_ARRIVAL',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
  VERIFIED_REFILLING = 'VERIFIED_REFILLING',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum NEGATIVE_KEYS {
  CLOSED = 'CLOSED',
  DAMAGED = 'DAMAGED',
  OFFLINE = 'OFFLINE',
  BLOQUED = 'BLOQUED',
  BLOCKED = 'BLOCKED',
  DELETED = 'DELETED',
  REMOVED = 'REMOVED',
  SUSPENDED = 'SUSPENDED',
  INOPERATIVE = 'INOPERATIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  INACTIVE = 'INACTIVE',
  NOT_OPERATIVE = 'NOT_OPERATIVE',
  DISABLED = 'DISABLED',
  CANCELLED = 'CANCELLED',
  NOT_AUTOMATED = 'NOT_AUTOMATED'
}

export enum ALERT_CRITICAL_KEYS {
  UNASSIGNED = 'UNASSIGNED',
  IN_MAINTENANCE = 'IN_MAINTENANCE',
  UNAVAILABLE = 'UNAVAILABLE',
  UNAFFILIATED = 'UNAFFILIATED',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum NEUTRAL_KEYS {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  INCOMING = 'INCOMING',
  AFFILIATED = 'AFFILIATED',
}
