import { ALERT_CRITICAL_KEYS, NEGATIVE_KEYS, NEUTRAL_KEYS, POSITIVE_KEYS, PROCESS_KEYS } from './common-status-keys'

const POSITIVE_KEYS_ARRAY = [
  POSITIVE_KEYS.OPEN,
  POSITIVE_KEYS.ONLINE,
  POSITIVE_KEYS.ACTIVE,
  POSITIVE_KEYS.DONE,
  POSITIVE_KEYS.VERIFIED,
  POSITIVE_KEYS.AVAILABLE,
  POSITIVE_KEYS.AFFILIATED,
  POSITIVE_KEYS.UPDATED,
  POSITIVE_KEYS.CREATED,
  POSITIVE_KEYS.OPERATIVE,
  POSITIVE_KEYS.ASSIGNED,
  POSITIVE_KEYS.COMPLETED,
  POSITIVE_KEYS.CONFIRMED,
  POSITIVE_KEYS.AUTOMATED,
  POSITIVE_KEYS.AFFILIATED,
]

const PROCESS_KEYS_ARRAY = [
  PROCESS_KEYS.IN_PROGRESS,
  PROCESS_KEYS.IN_PROCESS,
  PROCESS_KEYS.INCOMING,
  PROCESS_KEYS.IN_CHECK,
  PROCESS_KEYS.PENDING,
  PROCESS_KEYS.VERIFIED_ARRIVAL,
  PROCESS_KEYS.UNDER_MAINTENANCE,
  PROCESS_KEYS.UNDER_CONSTRUCTION,
  PROCESS_KEYS.VERIFIED_REFILLING,
  PROCESS_KEYS.PENDING_VERIFICATION,
]

const NEGATIVE_KEYS_ARRAY = [
  NEGATIVE_KEYS.CLOSED,
  NEGATIVE_KEYS.DAMAGED,
  NEGATIVE_KEYS.OFFLINE,
  NEGATIVE_KEYS.BLOQUED,
  NEGATIVE_KEYS.BLOCKED,
  NEGATIVE_KEYS.DELETED,
  NEGATIVE_KEYS.REMOVED,
  NEGATIVE_KEYS.SUSPENDED,
  NEGATIVE_KEYS.INOPERATIVE,
  NEGATIVE_KEYS.OUT_OF_STOCK,
  NEGATIVE_KEYS.INACTIVE,
  NEGATIVE_KEYS.DISABLED,
  NEGATIVE_KEYS.CANCELLED,
  NEGATIVE_KEYS.NOT_AUTOMATED,
]

const ALERT_CRITICAL_KEYS_ARRAY = [
  ALERT_CRITICAL_KEYS.UNASSIGNED,
  ALERT_CRITICAL_KEYS.UNAFFILIATED,
  ALERT_CRITICAL_KEYS.UNAVAILABLE,
  ALERT_CRITICAL_KEYS.OUT_OF_SERVICE,
  ALERT_CRITICAL_KEYS.UNDER_MAINTENANCE,
  ALERT_CRITICAL_KEYS.PENDING_VERIFICATION,
  ALERT_CRITICAL_KEYS.UNDER_CONSTRUCTION
]

const NEUTRAL_KEYS_ARRAY = [
  NEUTRAL_KEYS.CREATED,
  NEUTRAL_KEYS.UPDATED,
  NEUTRAL_KEYS.INCOMING,
]

export const getCommonBadgeColors = (status: string) => {
  if (POSITIVE_KEYS_ARRAY.includes(status as POSITIVE_KEYS)) {
    return 'rounded-full whitespace-nowrap bg-green-500/10 text-green-600 border border-green-500 hover:bg-green-600/20'
  }

  if (PROCESS_KEYS_ARRAY.includes(status as PROCESS_KEYS)) {
    return 'rounded-full whitespace-nowrap bg-blue-500/10 text-blue-600 border border-blue-500 hover:bg-blue-600/20'
  }

  if (NEGATIVE_KEYS_ARRAY.includes(status as NEGATIVE_KEYS)) {
    return 'rounded-full whitespace-nowrap bg-red-500/10 text-red-600 border border-red-500 hover:bg-red-600/20'
  }

  if (ALERT_CRITICAL_KEYS_ARRAY.includes(status as ALERT_CRITICAL_KEYS)) {
    return 'rounded-full whitespace-nowrap bg-orange-500/10 text-orange-600 border border-orange-500 hover:bg-orange-600/20'
  }

  if (NEUTRAL_KEYS_ARRAY.includes(status as NEUTRAL_KEYS)) {
    return 'rounded-full whitespace-nowrap bg-gray-500/10 text-gray-600 border border-gray-500 hover:bg-gray-600/20'
  }

  // Default color for statuses not explicitly defined
  return 'rounded-full whitespace-nowrap bg-gray-100 text-gray-500 border border-gray-200 hover:bg-gray-600/20'
}
