export const HEALTH_INSTITUTES_QUERY_KEYS = {
  TABLE: 'HEALTH_INSTITUTES_TABLE',
  DETAIL: 'HEALTH_INSTITUTES_DETAIL',
  CREATE: 'HEALTH_INSTITUTES_CREATE',
  EDIT: 'HEALTH_INSTITUTES_EDIT',
  DELETE: 'HEALTH_INSTITUTES_DELETE',
}