import { HEALTH_INSTITUTES_QUERY_KEYS } from './health-institutes'
import { MEDICAL_HISTORY_QUERY_KEYS } from './medical-history'
import { APPOINTMENTS_QUERY_KEYS } from './appointments'
import { TEMPLATE_QUERY_KEYS } from './templates'
import { PATIENT_QUERY_KEYS } from './patients'

export const QUERY_KEYS = {
  PATIENTS: PATIENT_QUERY_KEYS,
  TEMPLATES: TEMPLATE_QUERY_KEYS,
  APPOINTMENTS: APPOINTMENTS_QUERY_KEYS,
  MEDICAL_HISTORY: MEDICAL_HISTORY_QUERY_KEYS,
  HEALTH_INSTITUTES: HEALTH_INSTITUTES_QUERY_KEYS,
}