import { TRANSACTIONS_QUERY_KEYS } from './transactions'
import { CATEGORIES_QUERY_KEYS } from './categories'

export const QUERY_KEYS = {
  CATEGORIES: CATEGORIES_QUERY_KEYS,
  TRANSACTIONS: TRANSACTIONS_QUERY_KEYS,
}