export const MEDICAL_HISTORY_QUERY_KEYS = {
  TABLE: 'MEDICAL_HISTORY_TABLE',
  DETAIL: 'MEDICAL_HISTORY_DETAIL',
  CREATE: 'MEDICAL_HISTORY_CREATE',
  EDIT: 'MEDICAL_HISTORY_EDIT',
  DELETE: 'MEDICAL_HISTORY_DELETE',
}