export const TRANSACTIONS_QUERY_KEYS = {
  LIST: 'TRANSACTIONS_LIST',
  LIST_GROUPED: 'TRANSACTIONS_LIST_GROUPED',
  DETAIL: 'TRANSACTIONS_DETAIL',
  CREATE: 'TRANSACTIONS_CREATE',
  EDIT: 'TRANSACTIONS_EDIT',
  DELETE: 'TRANSACTIONS_DELETE',
}