export const TRANSACTIONS_QUERY_KEYS = {
  TABLE: 'TRANSACTIONS_TABLE',
  DETAIL: 'TRANSACTIONS_DETAIL',
  CREATE: 'TRANSACTIONS_CREATE',
  EDIT: 'TRANSACTIONS_EDIT',
  DELETE: 'TRANSACTIONS_DELETE',
}